#!/usr/bin/env bash
set -euo pipefail

printHelp()
{
    cat <<EOF
Open the remote repository in your browser.

Usage: repo
EOF
}

for i in "$@"
do
	case "$i" in
		-h|--help)
			printHelp
			exit
			;;
		-*)
			echo "Invalid option: $i"
			exit 1
            ;;
	esac
done

# Example remote:
# origin  git@gitlab.com:path/to/repo.git (fetch)

# Step by step:
# Only get the first line from the remotes.
# Remove everything up to the '@'.
# Remove everything from the '.git' url suffix.
# Replace the ':' with a '/'.
remoteUrl=$(git remote -v \
    | head -n 1 \
    | sed 's/.*@//' \
    | sed 's/\.git.*//' \
    | sed 's/:/\//' \
)
remoteUrl="https://$remoteUrl"

"$BROWSER" "$remoteUrl" &
